# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - carubbi-snake

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js version
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: Azure/webapps-deploy@v3
        with:
          app-name: 'carubbi-snake'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_891E36B2E7C64F769A7C76009AA41D42 }}
          package: .
